# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 893a41e7cac36b20936004c40fcaf43dae333e8b26f0ad22c77c8b85e09457c18d6edfc44c77f07227d0d4b89c08bb2ae6c526f16aea5ede6bf084977f7aeee6

test:
  secret_key_base: 543d0bb5ce409adbe66adfe37cb43fe16c0f33d3c43aa5444708995feb406b692174a218bdec52f77c27a36832a7d59b71ffd21133abf33c76402d3f50b643c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
